"""Add name to user model.

Revision ID: 70d631c75e08
Revises: 5ef995cd334d
Create Date: 2026-06-30 02:41:36.759544

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70d631c75e08"
down_revision: str | Sequence[str] | None = "5ef995cd334d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("name", sa.String(length=100), nullable=True), schema="async-pulse"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name", schema="async-pulse")
    # ### end Alembic commands ###
